PCB: false
batchsize: 32
color_jitter: false
data_dir: ./data/Market-1501-v15.09.15/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.06
name: ft_ResNet50
stride: 2
train_all: false
use_dense: false
